### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by renekorss** [jbox-web/job-database-manager-mysql#1]
Getting error on installing `.hpi`.

```
java.io.IOException: Failed to dynamically deploy this plugin
    at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:1383)
    at hudson.model.UpdateCenter$DownloadJob.run(UpdateCenter.java:1161)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at hudson.remoting.AtmostOneThreadExecutor$Worker.run(AtmostOneThreadExecutor.java:110)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Failed to install job-database-manager-mysql plugin
    at hudson.PluginManager.dynamicLoad(PluginManager.java:487)
    at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:1379)
    ... 5 more
Caused by: java.io.IOException: Dependency ruby-runtime (0.12) doesn't exist
    at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:533)
    at hudson.PluginManager.dynamicLoad(PluginManager.java:477)
    ... 6 more
```

Jenkins ver 1.643

**Comment by efarem** [comment]
I had this error, enabling the Ruby runtime plugin in Jenkins fixed it for me.

**Comment by n-rodriguez** [comment]
As @efarem said you need to install Jenkins Ruby runtime plugin.
